branches:
  only:
    - master

language: node_js

os:
  - linux

sudo: false

node_js:
  - "8"
  - "6"
  - "4"

matrix:
  fast_finish: true

git:
  depth: 1

before_install:
  - nvm install $NODE_VERSION

install:
  - npm install

script:
  - npm run build;
  - npm test;
