branches:
  only:
    - master

language: node_js

os:
  - linux

sudo: false

node_js:
  - "8"
  - "6"

matrix:
  fast_finish: true

git:
  depth: 1

install:
  - npm install
  - npm install coveralls --save-dev

script:
  - npm run build;
  - npm run nyc

after_success:
  - npm run coverage
